version: "3.9"

services:
  db:
    image: postgres
    ports:
      - 5431:5432
    hostname: db
    container_name: kanbango-db
    environment:
      POSTGRES_USER: kanbango
      POSTGRES_PASSWORD_FILE: /run/secrets/pass
      POSTGRES_DB: kanbango
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
    secrets:
      - pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q --username=kanbango"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "1m"
        max-file: "3"
  
  cache:
    image: redis
    restart: always
    hostname: cache
    container_name: kanbango-cache
    expose:
      - 6379
    logging:
        options:
          max-size: "1m"
          max-file: "3"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  auth:
    hostname: auth
    container_name: kanbango-auth
    build: .
    ports:
      - 50051:50051
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    
  
    

secrets:
  pass:
    file: internal/secrets/postgres-passwd.secret
